# Add 'root' label to any root file changes
root:
  - ./*
  
# Utilities Project Label
utilities:
  - packages/utilities/*
  - packages/utilities/**/*
  
# VSCode Project Label
vscode:
  - packages/vscode/*
  - packages/vscode/**/*  
  
# Karma Project Label
karma:
  - packages/karma/*
  - packages/karma/**/*
  
# Prettier Project Label
prettier:
  - packages/prettier/*
  - packages/prettier/**/*

# GitPod Project Label
gitpod:
  - packages/gitpod/*
  - packages/gitpod/**/*

# Husky Project Label
husky:
  - packages/husky/*
  - packages/husky/**/*

# Add 'test' label to any change to test specifications
test:
  - **/*.spec.ts

# Add 'docs` label to any change to a Markdown file
docs:
  - **/*.md
