tasks:
  - init: npm install -g @angular/cli @angular-devkit/schematics-cli @angular-devkit/schematics @angular-devkit/core @schematics/schematics lerna
    command: lerna bootstrap
image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - ms-vscode.vscode-typescript-tslint-plugin@1.2.3:MioHhlbqHKgivweg8MqHrA==
    - esbenp.prettier-vscode@3.20.0:37/f4uBlE287wUjENFq1aA==
    - christian-kohler.path-intellisense@1.4.2:QnOrf5fk6KiVaQs4cNEP+w==
    - EditorConfig.EditorConfig@0.14.4:EjFaoTaOf8wRmwR0LNY51A==
    - eg2.vscode-npm-script@0.3.11:peDPJqeL8FmmJiabU4fAJQ==
    - christian-kohler.npm-intellisense@1.3.0:yQtCdwoyo890Bn9NOEuEDA==
    - mikehuang.vscode-schematics-snippets@5.0.2:dQnyRLZj72bIIA+svsWq5A==
